Repository FAP-Cloud-Service/FAP-Infrastructure, pull requests merged in 2021-05, with the labels that each got.

#29 using default node pool
  infrastructure/kubernetes/main.tf
Labels: bug

#30 Release
  infrastructure/kubernetes/main.tf
Labels: PRIORITY

#34 changed vm size
  infrastructure/kubernetes/main.tf
Labels: bug

#35 Release
  infrastructure/kubernetes/main.tf
Labels: PRIORITY

#39 Add certificate permission and fix spelling
  infrastructure/secrets/main.tf
Labels: bug

#38 Use commit hash in zip name
  .github/workflows/terraform-deployment.yml
  .terraform.lock.hcl
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/output.tf
  infrastructure/main.tf
  infrastructure/secrets/main.tf
  infrastructure/variables.tf
  main.tf
  variables.tf
Labels: enhancement

#40 Release
  .github/workflows/terraform-deployment.yml
  .terraform.lock.hcl
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/output.tf
  infrastructure/main.tf
  infrastructure/secrets/main.tf
  infrastructure/variables.tf
  main.tf
  variables.tf
Labels: PRIORITY, Release, bug

#42 added app user object id to user list
  infrastructure/secrets/main.tf
Labels: bug

#44 Nested variables are not supported
  .github/workflows/terraform-deployment.yml
Labels: bug

#45 Add workflow_dispatch event trigger
  .github/workflows/terraform-deployment.yml
Labels: New Feature

#46 Release bugfixes
  .github/workflows/terraform-deployment.yml
  infrastructure/secrets/main.tf
Labels: PRIORITY, Release
