Repository FAP-Cloud-Service/FAP-Infrastructure, pull requests merged in 2021-04, with the labels that each got.

#8 Feature/add terraform project
  .terraform.lock.hcl
  README.md
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/main.tf
  infrastructure/variables.tf
  main.tf
  provider.tf
  variables.tf
  versions.tf
Labels: help wanted

#13 Pass env as input variable, set lock timeout for terraform apply
  .github/workflows/terraform-deployment.yml
Labels: bug

#15 Dont pass var to apply when saved plan is used
  .github/workflows/terraform-deployment.yml
Labels: bug

#16 Release 24.04.2021
  .github/workflows/terraform-deployment.yml
Labels: bug

#19 AKS-Cluster hinzugefügt | Key-Vault ergänzt
  .terraform.lock.hcl
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/main.tf
  infrastructure/kubernetes/output.tf
  infrastructure/kubernetes/variables.tf
  infrastructure/main.tf
  infrastructure/secrets/main.tf
  infrastructure/secrets/variables.tf
Labels: New Feature

#20 AKS Release
  .github/workflows/terraform-deployment.yml
  .terraform.lock.hcl
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/main.tf
  infrastructure/kubernetes/output.tf
  infrastructure/kubernetes/variables.tf
  infrastructure/main.tf
  infrastructure/secrets/main.tf
  infrastructure/secrets/variables.tf
  infrastructure/variables.tf
  main.tf
  provider.tf
  variables.tf
Labels: Release

#22 resolve config issues
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/output.tf
  infrastructure/secrets/main.tf
Labels: bug

#24 Bug Fixes und Deployment
  infrastructure/functions/main.tf
  infrastructure/functions/variables.tf
  infrastructure/kubernetes/output.tf
  infrastructure/secrets/main.tf
Labels: PRIORITY
